package parser

import "fugu/pkg/reporter"

func InitActionSlice() {
	action = []Action{
		Err(reporter.NoError), // 0
		Err(reporter.NoError), // 1
		Err(reporter.NoError), // 2
		Err(reporter.NoError), // 3
		Err(reporter.NoError), // 4
		Err(reporter.NoError), // 5
		Err(reporter.NoError), // 6
		Err(reporter.NoError), // 7
		Err(reporter.NoError), // 8
		Err(reporter.NoError), // 9
		Err(reporter.NoError), // 10
		Err(reporter.NoError), // 11
		Err(reporter.NoError), // 12
		Err(reporter.NoError), // 13
		Err(reporter.NoError), // 14
		Err(reporter.NoError), // 15
		Err(reporter.NoError), // 16
		Err(reporter.NoError), // 17
		Err(reporter.NoError), // 18
		Err(reporter.NoError), // 19
		Err(reporter.NoError), // 20
		Err(reporter.NoError), // 21
		Err(reporter.NoError), // 22
		Err(reporter.NoError), // 23
		Err(reporter.NoError), // 24
		Err(reporter.NoError), // 25
		Err(reporter.NoError), // 26
		Err(reporter.NoError), // 27
		Err(reporter.NoError), // 28
		Err(reporter.NoError), // 29
		Err(reporter.NoError), // 30
		Err(reporter.NoError), // 31
		Err(reporter.NoError), // 32
		Err(reporter.NoError), // 33
		Err(reporter.NoError), // 34
		Err(reporter.NoError), // 35
		Err(reporter.NoError), // 36
		Err(reporter.NoError), // 37
		Err(reporter.NoError), // 38
		Err(reporter.NoError), // 39
		Err(reporter.NoError), // 40
		Err(reporter.NoError), // 41
		Err(reporter.NoError), // 42
		Err(reporter.NoError), // 43
		Err(reporter.NoError), // 44
		Err(reporter.NoError), // 45
		Err(reporter.NoError), // 46
		Err(reporter.NoError), // 47
		Err(reporter.NoError), // 48
		Err(reporter.NoError), // 49
		Err(reporter.NoError), // 50
		Err(reporter.NoError), // 51
		Err(reporter.NoError), // 52
		Err(reporter.NoError), // 53
		Err(reporter.NoError), // 54
		Err(reporter.NoError), // 55
		Err(reporter.NoError), // 56
		Err(reporter.NoError), // 57
		Err(reporter.NoError), // 58
		Err(reporter.NoError), // 59
		Err(reporter.NoError), // 60
		Err(reporter.NoError), // 61
		Err(reporter.NoError), // 62
		Err(reporter.NoError), // 63
		Err(reporter.NoError), // 64
		Err(reporter.NoError), // 65
		Err(reporter.NoError), // 66
		Err(reporter.NoError), // 67
		Err(reporter.NoError), // 68
		Err(reporter.NoError), // 69
		Err(reporter.NoError), // 70
		Err(reporter.NoError), // 71
		Err(reporter.NoError), // 72
		Err(reporter.NoError), // 73
		Err(reporter.NoError), // 74
		Err(reporter.NoError), // 75
		Err(reporter.NoError), // 76
		Err(reporter.NoError), // 77
		Err(reporter.NoError), // 78
		Err(reporter.NoError), // 79
		Err(reporter.NoError), // 80
		Err(reporter.NoError), // 81
		Err(reporter.NoError), // 82
		Err(reporter.NoError), // 83
		Err(reporter.NoError), // 84
		Err(reporter.NoError), // 85
		Err(reporter.NoError), // 86
		Err(reporter.NoError), // 87
		Err(reporter.NoError), // 88
		Err(reporter.NoError), // 89
		Sh(3),                 // 90
		Err(reporter.NoError), // 91
		Err(reporter.NoError), // 92
		Err(reporter.NoError), // 93
		Err(reporter.NoError), // 94
		Err(reporter.NoError), // 95
		Err(reporter.NoError), // 96
		Err(reporter.NoError), // 97
		Err(reporter.NoError), // 98
		Err(reporter.NoError), // 99
		Err(reporter.NoError), // 100
		Sh(2),                 // 101
		Err(reporter.NoError), // 102
		Err(reporter.NoError), // 103
		Err(reporter.NoError), // 104
		Err(reporter.NoError), // 105
		Err(reporter.NoError), // 106
		Err(reporter.NoError), // 107
		Err(reporter.NoError), // 108
		Acc(),                 // 109
		Err(reporter.NoError), // 110
		Err(reporter.NoError), // 111
		Err(reporter.NoError), // 112
		Err(reporter.NoError), // 113
		Err(reporter.NoError), // 114
		Err(reporter.NoError), // 115
		Err(reporter.NoError), // 116
		Err(reporter.NoError), // 117
		Err(reporter.NoError), // 118
		Err(reporter.NoError), // 119
		Err(reporter.NoError), // 120
		Err(reporter.NoError), // 121
		Err(reporter.NoError), // 122
		Err(reporter.NoError), // 123
		Err(reporter.NoError), // 124
		Err(reporter.NoError), // 125
		Err(reporter.NoError), // 126
		Err(reporter.NoError), // 127
		Err(reporter.NoError), // 128
		Err(reporter.NoError), // 129
		Err(reporter.NoError), // 130
		Err(reporter.NoError), // 131
		Err(reporter.NoError), // 132
		Err(reporter.NoError), // 133
		Err(reporter.NoError), // 134
		Err(reporter.NoError), // 135
		Err(reporter.NoError), // 136
		Err(reporter.NoError), // 137
		Err(reporter.NoError), // 138
		Err(reporter.NoError), // 139
		Err(reporter.NoError), // 140
		Err(reporter.NoError), // 141
		Err(reporter.NoError), // 142
		Err(reporter.NoError), // 143
		Err(reporter.NoError), // 144
		Err(reporter.NoError), // 145
		Err(reporter.NoError), // 146
		Err(reporter.NoError), // 147
		Err(reporter.NoError), // 148
		Err(reporter.NoError), // 149
		Err(reporter.NoError), // 150
		Err(reporter.NoError), // 151
		Err(reporter.NoError), // 152
		Err(reporter.NoError), // 153
		Err(reporter.NoError), // 154
		Err(reporter.NoError), // 155
		Err(reporter.NoError), // 156
		Err(reporter.NoError), // 157
		Err(reporter.NoError), // 158
		Err(reporter.NoError), // 159
		Err(reporter.NoError), // 160
		Err(reporter.NoError), // 161
		Err(reporter.NoError), // 162
		Err(reporter.NoError), // 163
		Err(reporter.NoError), // 164
		Err(reporter.NoError), // 165
		Err(reporter.NoError), // 166
		Err(reporter.NoError), // 167
		Err(reporter.NoError), // 168
		Err(reporter.NoError), // 169
		Err(reporter.NoError), // 170
		Err(reporter.NoError), // 171
		Err(reporter.NoError), // 172
		Err(reporter.NoError), // 173
		Err(reporter.NoError), // 174
		Err(reporter.NoError), // 175
		Err(reporter.NoError), // 176
		Err(reporter.NoError), // 177
		Err(reporter.NoError), // 178
		Err(reporter.NoError), // 179
		Err(reporter.NoError), // 180
		Err(reporter.NoError), // 181
		Err(reporter.NoError), // 182
		Err(reporter.NoError), // 183
		Err(reporter.NoError), // 184
		Err(reporter.NoError), // 185
		Err(reporter.NoError), // 186
		Err(reporter.NoError), // 187
		Err(reporter.NoError), // 188
		Err(reporter.NoError), // 189
		Err(reporter.NoError), // 190
		Err(reporter.NoError), // 191
		Err(reporter.NoError), // 192
		Err(reporter.NoError), // 193
		Err(reporter.NoError), // 194
		Err(reporter.NoError), // 195
		Err(reporter.NoError), // 196
		Err(reporter.NoError), // 197
		Err(reporter.NoError), // 198
		Err(reporter.NoError), // 199
		Err(reporter.NoError), // 200
		Err(reporter.NoError), // 201
		Err(reporter.NoError), // 202
		Err(reporter.NoError), // 203
		Err(reporter.NoError), // 204
		Err(reporter.NoError), // 205
		Err(reporter.NoError), // 206
		Sh(4),                 // 207
		Err(reporter.NoError), // 208
		Err(reporter.NoError), // 209
		Err(reporter.NoError), // 210
		Err(reporter.NoError), // 211
		Err(reporter.NoError), // 212
		Red(6),                // 213
		Err(reporter.NoError), // 214
		Err(reporter.NoError), // 215
		Err(reporter.NoError), // 216
		Err(reporter.NoError), // 217
		Err(reporter.NoError), // 218
		Err(reporter.NoError), // 219
		Err(reporter.NoError), // 220
		Err(reporter.NoError), // 221
		Err(reporter.NoError), // 222
		Err(reporter.NoError), // 223
		Err(reporter.NoError), // 224
		Err(reporter.NoError), // 225
		Err(reporter.NoError), // 226
		Err(reporter.NoError), // 227
		Err(reporter.NoError), // 228
		Err(reporter.NoError), // 229
		Err(reporter.NoError), // 230
		Err(reporter.NoError), // 231
		Err(reporter.NoError), // 232
		Err(reporter.NoError), // 233
		Err(reporter.NoError), // 234
		Err(reporter.NoError), // 235
		Err(reporter.NoError), // 236
		Err(reporter.NoError), // 237
		Err(reporter.NoError), // 238
		Err(reporter.NoError), // 239
		Err(reporter.NoError), // 240
		Err(reporter.NoError), // 241
		Err(reporter.NoError), // 242
		Err(reporter.NoError), // 243
		Err(reporter.NoError), // 244
		Err(reporter.NoError), // 245
		Err(reporter.NoError), // 246
		Err(reporter.NoError), // 247
		Err(reporter.NoError), // 248
		Err(reporter.NoError), // 249
		Err(reporter.NoError), // 250
		Err(reporter.NoError), // 251
		Err(reporter.NoError), // 252
		Err(reporter.NoError), // 253
		Err(reporter.NoError), // 254
		Err(reporter.NoError), // 255
		Err(reporter.NoError), // 256
		Err(reporter.NoError), // 257
		Err(reporter.NoError), // 258
		Err(reporter.NoError), // 259
		Err(reporter.NoError), // 260
		Err(reporter.NoError), // 261
		Err(reporter.NoError), // 262
		Err(reporter.NoError), // 263
		Err(reporter.NoError), // 264
		Err(reporter.NoError), // 265
		Err(reporter.NoError), // 266
		Err(reporter.NoError), // 267
		Err(reporter.NoError), // 268
		Err(reporter.NoError), // 269
		Err(reporter.NoError), // 270
		Err(reporter.NoError), // 271
		Err(reporter.NoError), // 272
		Err(reporter.NoError), // 273
		Err(reporter.NoError), // 274
		Err(reporter.NoError), // 275
		Err(reporter.NoError), // 276
		Err(reporter.NoError), // 277
		Err(reporter.NoError), // 278
		Err(reporter.NoError), // 279
		Err(reporter.NoError), // 280
		Err(reporter.NoError), // 281
		Err(reporter.NoError), // 282
		Err(reporter.NoError), // 283
		Err(reporter.NoError), // 284
		Err(reporter.NoError), // 285
		Err(reporter.NoError), // 286
		Err(reporter.NoError), // 287
		Err(reporter.NoError), // 288
		Err(reporter.NoError), // 289
		Err(reporter.NoError), // 290
		Err(reporter.NoError), // 291
		Err(reporter.NoError), // 292
		Err(reporter.NoError), // 293
		Err(reporter.NoError), // 294
		Err(reporter.NoError), // 295
		Err(reporter.NoError), // 296
		Err(reporter.NoError), // 297
		Err(reporter.NoError), // 298
		Red(6),                // 299
		Err(reporter.NoError), // 300
		Err(reporter.NoError), // 301
		Err(reporter.NoError), // 302
		Err(reporter.NoError), // 303
		Err(reporter.NoError), // 304
		Err(reporter.NoError), // 305
		Err(reporter.NoError), // 306
		Err(reporter.NoError), // 307
		Err(reporter.NoError), // 308
		Err(reporter.NoError), // 309
		Err(reporter.NoError), // 310
		Red(6),                // 311
		Err(reporter.NoError), // 312
		Err(reporter.NoError), // 313
		Err(reporter.NoError), // 314
		Err(reporter.NoError), // 315
		Err(reporter.NoError), // 316
		Err(reporter.NoError), // 317
		Err(reporter.NoError), // 318
		Err(reporter.NoError), // 319
		Err(reporter.NoError), // 320
		Err(reporter.NoError), // 321
		Err(reporter.NoError), // 322
		Err(reporter.NoError), // 323
		Err(reporter.NoError), // 324
		Err(reporter.NoError), // 325
		Err(reporter.NoError), // 326
		Err(reporter.NoError), // 327
		Err(reporter.NoError), // 328
		Err(reporter.NoError), // 329
		Err(reporter.NoError), // 330
		Err(reporter.NoError), // 331
		Err(reporter.NoError), // 332
		Err(reporter.NoError), // 333
		Err(reporter.NoError), // 334
		Err(reporter.NoError), // 335
		Err(reporter.NoError), // 336
		Err(reporter.NoError), // 337
		Err(reporter.NoError), // 338
		Err(reporter.NoError), // 339
		Err(reporter.NoError), // 340
		Err(reporter.NoError), // 341
		Err(reporter.NoError), // 342
		Err(reporter.NoError), // 343
		Err(reporter.NoError), // 344
		Err(reporter.NoError), // 345
		Err(reporter.NoError), // 346
		Err(reporter.NoError), // 347
		Err(reporter.NoError), // 348
		Err(reporter.NoError), // 349
		Err(reporter.NoError), // 350
		Err(reporter.NoError), // 351
		Err(reporter.NoError), // 352
		Err(reporter.NoError), // 353
		Err(reporter.NoError), // 354
		Err(reporter.NoError), // 355
		Err(reporter.NoError), // 356
		Err(reporter.NoError), // 357
		Err(reporter.NoError), // 358
		Err(reporter.NoError), // 359
		Err(reporter.NoError), // 360
		Err(reporter.NoError), // 361
		Err(reporter.NoError), // 362
		Err(reporter.NoError), // 363
		Err(reporter.NoError), // 364
		Err(reporter.NoError), // 365
		Err(reporter.NoError), // 366
		Err(reporter.NoError), // 367
		Err(reporter.NoError), // 368
		Err(reporter.NoError), // 369
		Err(reporter.NoError), // 370
		Err(reporter.NoError), // 371
		Err(reporter.NoError), // 372
		Err(reporter.NoError), // 373
		Err(reporter.NoError), // 374
		Err(reporter.NoError), // 375
		Err(reporter.NoError), // 376
		Err(reporter.NoError), // 377
		Err(reporter.NoError), // 378
		Err(reporter.NoError), // 379
		Err(reporter.NoError), // 380
		Err(reporter.NoError), // 381
		Err(reporter.NoError), // 382
		Err(reporter.NoError), // 383
		Err(reporter.NoError), // 384
		Err(reporter.NoError), // 385
		Err(reporter.NoError), // 386
		Err(reporter.NoError), // 387
		Err(reporter.NoError), // 388
		Err(reporter.NoError), // 389
		Err(reporter.NoError), // 390
		Err(reporter.NoError), // 391
		Err(reporter.NoError), // 392
		Err(reporter.NoError), // 393
		Err(reporter.NoError), // 394
		Err(reporter.NoError), // 395
		Err(reporter.NoError), // 396
		Err(reporter.NoError), // 397
		Err(reporter.NoError), // 398
		Err(reporter.NoError), // 399
		Err(reporter.NoError), // 400
		Err(reporter.NoError), // 401
		Sh(3),                 // 402
		Err(reporter.NoError), // 403
		Err(reporter.NoError), // 404
		Err(reporter.NoError), // 405
		Err(reporter.NoError), // 406
		Err(reporter.NoError), // 407
		Err(reporter.NoError), // 408
		Err(reporter.NoError), // 409
		Err(reporter.NoError), // 410
		Err(reporter.NoError), // 411
		Err(reporter.NoError), // 412
		Sh(2),                 // 413
		Err(reporter.NoError), // 414
		Err(reporter.NoError), // 415
		Err(reporter.NoError), // 416
		Err(reporter.NoError), // 417
		Err(reporter.NoError), // 418
		Err(reporter.NoError), // 419
		Err(reporter.NoError), // 420
		Err(reporter.NoError), // 421
		Err(reporter.NoError), // 422
		Err(reporter.NoError), // 423
		Err(reporter.NoError), // 424
		Err(reporter.NoError), // 425
		Err(reporter.NoError), // 426
		Err(reporter.NoError), // 427
		Err(reporter.NoError), // 428
		Err(reporter.NoError), // 429
		Err(reporter.NoError), // 430
		Err(reporter.NoError), // 431
		Err(reporter.NoError), // 432
		Err(reporter.NoError), // 433
		Err(reporter.NoError), // 434
		Err(reporter.NoError), // 435
		Err(reporter.NoError), // 436
		Err(reporter.NoError), // 437
		Err(reporter.NoError), // 438
		Err(reporter.NoError), // 439
		Err(reporter.NoError), // 440
		Err(reporter.NoError), // 441
		Err(reporter.NoError), // 442
		Err(reporter.NoError), // 443
		Err(reporter.NoError), // 444
		Err(reporter.NoError), // 445
		Err(reporter.NoError), // 446
		Err(reporter.NoError), // 447
		Err(reporter.NoError), // 448
		Err(reporter.NoError), // 449
		Err(reporter.NoError), // 450
		Err(reporter.NoError), // 451
		Err(reporter.NoError), // 452
		Err(reporter.NoError), // 453
		Err(reporter.NoError), // 454
		Err(reporter.NoError), // 455
		Err(reporter.NoError), // 456
		Err(reporter.NoError), // 457
		Err(reporter.NoError), // 458
		Err(reporter.NoError), // 459
		Err(reporter.NoError), // 460
		Err(reporter.NoError), // 461
		Err(reporter.NoError), // 462
		Err(reporter.NoError), // 463
		Err(reporter.NoError), // 464
		Err(reporter.NoError), // 465
		Err(reporter.NoError), // 466
		Err(reporter.NoError), // 467
		Err(reporter.NoError), // 468
		Err(reporter.NoError), // 469
		Err(reporter.NoError), // 470
		Err(reporter.NoError), // 471
		Err(reporter.NoError), // 472
		Err(reporter.NoError), // 473
		Err(reporter.NoError), // 474
		Err(reporter.NoError), // 475
		Err(reporter.NoError), // 476
		Err(reporter.NoError), // 477
		Err(reporter.NoError), // 478
		Err(reporter.NoError), // 479
		Err(reporter.NoError), // 480
		Err(reporter.NoError), // 481
		Err(reporter.NoError), // 482
		Err(reporter.NoError), // 483
		Err(reporter.NoError), // 484
		Err(reporter.NoError), // 485
		Err(reporter.NoError), // 486
		Err(reporter.NoError), // 487
		Err(reporter.NoError), // 488
		Err(reporter.NoError), // 489
		Err(reporter.NoError), // 490
		Err(reporter.NoError), // 491
		Err(reporter.NoError), // 492
		Err(reporter.NoError), // 493
		Err(reporter.NoError), // 494
		Err(reporter.NoError), // 495
		Err(reporter.NoError), // 496
		Err(reporter.NoError), // 497
		Err(reporter.NoError), // 498
		Err(reporter.NoError), // 499
		Err(reporter.NoError), // 500
		Err(reporter.NoError), // 501
		Err(reporter.NoError), // 502
		Err(reporter.NoError), // 503
		Err(reporter.NoError), // 504
		Err(reporter.NoError), // 505
		Sh(3),                 // 506
		Err(reporter.NoError), // 507
		Err(reporter.NoError), // 508
		Err(reporter.NoError), // 509
		Err(reporter.NoError), // 510
		Err(reporter.NoError), // 511
		Err(reporter.NoError), // 512
		Err(reporter.NoError), // 513
		Err(reporter.NoError), // 514
		Err(reporter.NoError), // 515
		Err(reporter.NoError), // 516
		Sh(2),                 // 517
		Err(reporter.NoError), // 518
		Err(reporter.NoError), // 519
	}
}
