name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Build
      run: |
        cd fugu
        go mod download
        go generate ./pkg/parse/actionr
        go build -v ./...

    - name: Test
      run: |
        cd fugu
        go test -v -race ./...
